# coot script generated by dimple
#set_nomenclature_errors_on_read("ignore")
molecule = read_pdb('final.pdb')
set_rotation_centre(-9.45, -31.18, 2.21)
set_zoom(30.)
set_view_quaternion(0.437014, 0.0185956, 0, 0.899262)
mtz = 'final.mtz'
map21 = make_and_draw_map(mtz, "2FOFCWT", "PH2FOFCWT", "", 0, 0)
map11 = make_and_draw_map(mtz, "FOFCWT", "PHFOFCWT", "", 0, 1)